name: PHPUnit

on:
  push:
  pull_request:
  schedule:
    - cron: '0 14 * * 3' # Run Wednesdays at 2pm EST

jobs:
  php-tests:
    strategy:
      matrix:
        dependency-version: [ stable, lowest ]
        os: [ ubuntu-latest, windows-latest ]
        laravel: [ ^8.79, ^9.34, 10.* ]
        php: [ 8.0, 8.1, 8.2 ]
        exclude:
          - php: 8.2
            laravel: ^8.79
          - php: 8.0
            laravel: 10.*

    runs-on: ${{ matrix.os }}
    timeout-minutes: 10

    name: "${{ matrix.os }} Laravel:${{ matrix.laravel }} PHP:${{ matrix.php }} (${{ matrix.dependency-version }})"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, bcmath, intl, iconv, fileinfo
          tools: composer:v2

      - name: Register composer cache directory
        id: composer-cache-files-dir
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: |
            vendor
            ${{ steps.composer-cache-files-dir.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('composer.json') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Set minimum stability
        run: composer config minimum-stability ${{ matrix.minimum-stability }}

      - name: Install dependencies
        env:
          COMPOSER_DISCARD_CHANGES: true
        run: composer require --no-interaction --prefer-dist --no-update "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench"

      - name: Set dependency version
        env:
          COMPOSER_DISCARD_CHANGES: true
        run: composer update --no-interaction --prefer-dist --with-all-dependencies --prefer-${{ matrix.dependency-version }}

      - name: Execute tests
        run: vendor/bin/phpunit -v
